-dontwarn com.google.mediapipe.**
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite { *; }
-keep class com.google.mediapipe.** { *; }
-keep class com.google.common.flogger.** { *; }